### ISSUE TITLE
Hydra Override Parsing Error : mismatched input 'tennis_smoothed.pkl' expecting ID

### ISSUE THREAD

**Issue by bring-nirachornkul** [Skype-line/X-Avatar#21]
Hi, everyone.

I encountered this error, when I try to run `python demo.py subject=00034_rgbd experiments=XHumans_occ_smplx demo.motion_path= download/demo_motion_sequence/tennis_smoothed.pkl`

Here is the error message : 

```
(xavatar) blinkdrive@blinkdrive-System-Product-Name:~/Documents/UNT/Project/X-Avatar/code$ python demo.py subject=00034_rgbd experiments=XHumans_occ_smplx demo.motion_path= download/demo_motion_sequence/tennis_smoothed.pkl
Traceback (most recent call last):
  File "demo.py", line 110, in <module>
    main()
  File "/home/blinkdrive/anaconda3/envs/xavatar/lib/python3.7/site-packages/hydra/main.py", line 52, in decorated_main
    config_name=config_name,
  File "/home/blinkdrive/anaconda3/envs/xavatar/lib/python3.7/site-packages/hydra/_internal/utils.py", line 378, in _run_hydra
    lambda: hydra.run(
  File "/home/blinkdrive/anaconda3/envs/xavatar/lib/python3.7/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/home/blinkdrive/anaconda3/envs/xavatar/lib/python3.7/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/blinkdrive/anaconda3/envs/xavatar/lib/python3.7/site-packages/hydra/_internal/utils.py", line 381, in <lambda>
    overrides=args.overrides,
  File "/home/blinkdrive/anaconda3/envs/xavatar/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 92, in run
    run_mode=RunMode.RUN,
  File "/home/blinkdrive/anaconda3/envs/xavatar/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 563, in compose_config
    from_shell=from_shell,
  File "/home/blinkdrive/anaconda3/envs/xavatar/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 145, in load_configuration
    from_shell=from_shell,
  File "/home/blinkdrive/anaconda3/envs/xavatar/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 231, in _load_configuration_impl
    parsed_overrides = parser.parse_overrides(overrides=overrides)
  File "/home/blinkdrive/anaconda3/envs/xavatar/lib/python3.7/site-packages/hydra/core/override_parser/overrides_parser.py", line 100, in parse_overrides
    ) from e.__cause__
hydra.errors.OverrideParseException: mismatched input 'tennis_smoothed.pkl' expecting ID
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

```

The main error is ` mismatched input 'tennis_smoothed.pkl' expecting ID`.

What is the subject ID should I put for or did I miss anythings here?

**Comment by MoyGcc** [comment]
Hi, is there any problem when you run on `00085_scan`?

**Comment by bring-nirachornkul** [comment]
> Hi, is there any problem when you run on `00085_scan`?

Nope, not at all. I think the problem is about environment directory that I need to type it correctly otherwise this error gonna show up.
