### ISSUE TITLE
ImportError: cannot import name 'mise' from 'lib.libmise' (unknown location)

### ISSUE THREAD

**Issue by justinvo277** [Skype-line/X-Avatar#25]
Traceback (most recent call last):
  File "demo.py", line 18, in <module>
    from lib.xavatar_scan_model import XAVATARSCANModel
  File "D:\Models\X-Avatar_folder\X-Avatar\code\lib\xavatar_scan_model.py", line 3, in <module>
    from lib.xavatar_basic_model import XAVATARModel
  File "D:\Models\X-Avatar_folder\X-Avatar\code\lib\xavatar_basic_model.py", line 14, in <module>
    from lib.utils.meshing import generate_mesh
  File "D:\Models\X-Avatar_folder\X-Avatar\code\lib\utils\meshing.py", line 4, in <module>
    from lib.libmise import mise
ImportError: cannot import name 'mise' from 'lib.libmise' (unknown location)

Please help me solve this problem

**Comment by MoyGcc** [comment]
Hi, you should first build the mise lib as stated here: https://github.com/Skype-line/X-Avatar?tab=readme-ov-file#prerequisites
